DECLARE
VCOUNT NUMBER(2);
VSUM NUMBER(2):=0;
V_AVG NUMBER(3,2);
BEGIN
VCOUNT:=1;
LOOP
VSUM:=VSUM+VCOUNT;
VCOUNT:=VCOUNT+1;
EXIT WHEN VCOUNT>10;
END LOOP;
V_AVG:=VSUM/(VCOUNT-1);
DBMS_OUTPUT.PUT_LINE('AVERAGE OF 1 TO 10 IS : '||V_AVG);
END;
/
