DECLARE
    S NUMBER(3):=&SCORE;
    GRADE CHAR;
    BEGIN
    IF S>=90 AND S<=100 THEN GRADE:='A';
    ELSE  IF S>=80 AND S<90 THEN GRADE:='B';
    ELSE  IF S>=70 AND S<80 THEN GRADE:='C';
    ELSE  IF S>=60 AND S<70 THEN GRADE:='D';
    ELSE IF S>0 THEN GRADE:='F';
   ELSE  IF S<0 AND S>100 THEN GRADE:='U';
   END IF;
   DBMS_OUTPUT.PUT_LINE('SCORE IS' ||S);
   DBMS_OUTPUT.PUT_LINE('GRADE IS' ||GRADE);
   END;
   /
