DECLARE
  2  S NUMBER(3):=&SCORE;
  3  GRADE CHAR;
  4  BEGIN
  5  IF S>=90 AND S<=100 THEN GRADE:='A';
  6  ELSE  IF S>=80 AND S<90 THEN GRADE:='B';
  7  ELSE  IF S>=70 AND S<80 THEN GRADE:='C';
  8  ELSE  IF S>=60 AND S<70 THEN GRADE:='D';
  9  ELSE IF S>0 THEN GRADE:='F';
 10  ELSE  IF S<0 AND S>100 THEN GRADE:='U';
 11  END IF;
 12  DBMS_OUTPUT.PUT_LINE('SCORE IS' ||S);
 13  DBMS_OUTPUT.PUT_LINE('GRADE IS' ||GRADE);
 14  END;
 15  /
